### ISSUE TITLE
Friends Requests and Notifications popups stay on screen

### ISSUE THREAD

**Issue by jbrucker** [whsatku/social#111]
After clicking on the friends request icon or notification icon (top-right of screen),
the popup that appears stays visible until user clicks on the icon again.
Clicking elsewhere on the page does not remove the popup.
Is this the intended behavior?

**Comment by whs** [comment]
This behavior is intended and this concern has been raised from the
notification development team. Binding site-wide event listener in Angular
require some effort unless we want to do it in non-standard style.

I could see that it results in poor user experience though, so I'll put
this under consideration for now.
