### ISSUE TITLE
Profile image

### ISSUE THREAD

**Issue by Av0cadoo** [whsatku/social#139]
Show profile image is incorrect.

**Comment by vasupol11** [comment]
the profile image works now, but just wrong size.

**Comment by yoyothai00** [comment]
"not correct" ??

**Comment by vasupol11** [comment]
incorrectly

**Comment by vasupol11** [comment]
it works now, I tried, but can you confirm? Just wrong size as far as im concern

**Comment by Av0cadoo** [comment]
For me, on my profile page it work correctly.

**Comment by Av0cadoo** [comment]
Some image is rotate counter clocwise
