### ISSUE TITLE
[#98-EV] Fix date format from angular to django

### ISSUE THREAD

**Issue by vasupol11** [whsatku/social#98]

**Comment by whs** [comment]
Which branch and file are you working on?

**Comment by vasupol11** [comment]
On branch event. Yesterday jeng merged staging into event. Theres problem, so jeng asked if you could merge. So i deleted the one he merged and uploaded the old one.

**Comment by vasupol11** [comment]
Another thing, in event model the field is datetimefield. We were trying out something but forgot to change back to datefield incase you were wondering.
